packages:
hello_package:
actions:
say_hello:
location: src/hello_function.js
runtime: nodejs:6
inputs:
greeting: "Hello"
user: "World"
triggers:
greeting_trigger:
feed: @FEED_BASE@/messageHubFeed
inputs:
isJSONData: string
topic: GreetAll
rules:
greeting_rule:
action: say_hello
trigger: greeting_trigger
